apiVersion: v1
kind: ConfigMap
metadata:
  name: twin-cs-configmap
  namespace: dt
data:
  init.sh: |
    #!/bin/bash

    mongosh admin -u dt -p dt --eval "use confTwins" --eval "db.createUser({ user: \"dt\", pwd: \"dt\",roles: [ { role: \"readWrite\", db: \"confTwins\" }]})"