---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cs-data
  namespace: dt
  labels:
    app.kubernetes.io/name: files
    app.kubernetes.io/version: "1.1"
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 6G

